import { MenuItem } from "./types";

export const MENU_ITEMS: readonly MenuItem[] = [
  // Sushi Rolls
  {
    id: "salmon-roll",
    name: "Salmon Roll",
    description: "Fresh Atlantic salmon with avocado and cucumber, wrapped in seasoned rice and nori.",
    price: 8,
    category: "Sushi Rolls",
    image: "/images/salmon-roll.jpg",
    isPopular: true,
  },
  {
    id: "tuna-roll",
    name: "Tuna Roll",
    description: "Premium tuna with spring onion and spicy mayo, rolled in sushi rice.",
    price: 9,
    category: "Sushi Rolls",
    image: "/images/tuna-roll.jpg",
  },
  {
    id: "california-roll",
    name: "California Roll",
    description: "Classic inside-out roll with crab stick, avocado, and cucumber.",
    price: 7,
    category: "Sushi Rolls",
    image: "/images/california-roll.jpg",
    isPopular: true,
  },
  {
    id: "dragon-roll",
    name: "Dragon Roll",
    description: "Eel and cucumber inside, topped with sliced avocado and unagi sauce.",
    price: 12,
    category: "Sushi Rolls",
    image: "/images/dragon-roll.jpg",
  },
  {
    id: "veggie-roll",
    name: "Veggie Roll",
    description: "Avocado, cucumber, carrot, and pickled radish wrapped in sushi rice.",
    price: 7,
    category: "Sushi Rolls",
    image: "/images/veggie-roll.jpg",
  },

  // Nigiri
  {
    id: "salmon-nigiri",
    name: "Salmon Nigiri",
    description: "Two pieces of fresh salmon over pressed sushi rice.",
    price: 6,
    category: "Nigiri",
    image: "/images/salmon-nigiri.jpg",
  },
  {
    id: "tuna-nigiri",
    name: "Tuna Nigiri",
    description: "Two pieces of premium tuna over pressed sushi rice.",
    price: 7,
    category: "Nigiri",
    image: "/images/tuna-nigiri.jpg",
  },
  {
    id: "prawn-nigiri",
    name: "Prawn Nigiri",
    description: "Two pieces of cooked prawn over pressed sushi rice.",
    price: 7,
    category: "Nigiri",
    image: "/images/prawn-nigiri.jpg",
  },
  {
    id: "eel-nigiri",
    name: "Eel Nigiri",
    description: "Two pieces of glazed eel over pressed sushi rice with unagi sauce.",
    price: 8,
    category: "Nigiri",
    image: "/images/eel-nigiri.jpg",
  },

  // Starters
  {
    id: "gyoza",
    name: "Gyoza",
    description: "Pan-fried pork dumplings served with soy dipping sauce.",
    price: 7,
    category: "Starters",
    image: "/images/gyoza.jpg",
    isPopular: true,
  },
  {
    id: "edamame",
    name: "Edamame",
    description: "Steamed soybean pods sprinkled with sea salt.",
    price: 5,
    category: "Starters",
    image: "/images/edamame.jpg",
  },
  {
    id: "miso-soup",
    name: "Miso Soup",
    description: "Traditional Japanese soup with tofu, wakame seaweed, and spring onion.",
    price: 4,
    category: "Starters",
    image: "/images/miso-soup.jpg",
  },
  {
    id: "prawn-tempura",
    name: "Prawn Tempura",
    description: "Crispy battered prawns served with tempura dipping sauce.",
    price: 9,
    category: "Starters",
    image: "/images/prawn-tempura.jpg",
  },

  // Specials
  {
    id: "sashimi-platter",
    name: "Sashimi Platter",
    description: "Chef's selection of premium sliced fish — salmon, tuna, and yellowtail.",
    price: 18,
    category: "Specials",
    image: "/images/sashimi-platter.jpg",
  },
  {
    id: "maki-combo",
    name: "Maki Combo",
    description: "A generous assortment of our most popular maki rolls.",
    price: 22,
    category: "Specials",
    image: "/images/maki-combo.jpg",
    isPopular: true,
  },
  {
    id: "chefs-special",
    name: "Chef's Special",
    description: "An exquisite omakase-style platter curated by our head chef.",
    price: 25,
    category: "Specials",
    image: "/images/chefs-special.jpg",
  },

  // Desserts
  {
    id: "brownie",
    name: "Brownie",
    description: "Rich chocolate brownie served warm with a dusting of powdered sugar.",
    price: 6,
    category: "Desserts",
    image: "/images/brownie.jpg",
  },
  {
    id: "mochi",
    name: "Mochi",
    description: "Soft Japanese rice cake with sweet red bean filling.",
    price: 5,
    category: "Desserts",
    image: "/images/mochi.jpg",
  },
  {
    id: "matcha-cheesecake",
    name: "Matcha Cheesecake",
    description: "Creamy cheesecake infused with premium matcha green tea.",
    price: 7,
    category: "Desserts",
    image: "/images/matcha-cheesecake.jpg",
  },
] as const;
